---
- name: Configure my machine
  hosts: local
  vars:
    # Resolve the home directory to its physical path
    physical_home: "{{ ansible_user_dir | realpath }}"

    # Dynamic Path Discovery
    # - `playbook_dir` is `/path/to/repo/ansible`
    # - `repo_root` will be `/path/to/repo`
    # - `repo_name` will be `repo`
    repo_root: "{{ (playbook_dir | dirname) | realpath }}"
    repo_name: "{{ repo_root | basename }}"

    # Workspace Definitions
    workspace_root: "{{ physical_home }}/Workspace"
    personal_dir: "{{ workspace_root }}/personal"
    work_dir: "{{ workspace_root }}/work"

    # We define where the repo SHOULD be based on its current folder name
    expected_repo_root: "{{ (personal_dir ~ '/' ~ repo_name) | realpath }}"

    # TODO:
    # - .emacs.d
    # - .unison
    # - Library
    # - .bash_profile
    # - .bashrc
    # - .rtorrent.rc
    repo_conf_files:
      - .alias
      - .emacs
      - .git-commit-template
      - .gitconfig
      - .gitconfig-aliases.sh
      - .gitconfig.amzn
      - .tmux.conf
      - .zsh.d
      - .zshenv
      - .zshrc

    untracked_conf_files:
      - .fzf
      - .oh-my-zsh
      - .zsh_history
  tasks:
    - name: Ensure Workspace structure exists
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ ansible_user_dir }}/Workspace"
        - "{{ ansible_user_dir }}/Workspace/personal"
        - "{{ ansible_user_dir }}/Workspace/work"  # [ONLY FOR AMZN CDD] Add symlink to /local/workplace/vmous

    - name: Verify repository location
      ansible.builtin.assert:
        that:
          - repo_root == expected_repo_root
        fail_msg: |
          ERROR: '{{ repo_name }}' is in the wrong place. Move and try again
          Current: {{ repo_root }}
          Expected: {{ expected_repo_root }}
        success_msg: "Confirmed: '{{ repo_name }}' is correctly located under '{{ expected_repo_root }}'."

    - name: MacOS-specific configuration
      import_tasks: macos.yml
      when: ansible_os_family == "Darwin"

    - name: Linux-specific configuration
      import_tasks: linux.yml
      when: ansible_os_family == "RedHat"

    - name: Scan for repo configuration files/directories
      ansible.builtin.stat:
        path: "{{ ansible_user_dir }}/{{ item }}"
      loop: "{{ repo_conf_files }}"
      register: repo_conf_files_stats

    - name: Backup existing repo configuration files/directories
      ansible.builtin.command:
        cmd: "mv {{ ansible_user_dir }}/{{ item.item }} {{ ansible_user_dir }}/{{ item.item }}.ORIG"
      loop: "{{ repo_conf_files_stats.results }}"
      when:
        - item.stat.exists
        - not item.stat.islnk
      loop_control:
        # Only print limitted info in the output instead of the whole object
        label: "{{ item.item }}"

    - name: Create symbolic links to repo configuration files/directories
      ansible.builtin.file:
        src: "{{ playbook_dir | dirname }}/{{ item }}"
        dest: "{{ ansible_user_dir }}/{{ item }}"
        state: link
        force: yes
      loop: "{{ repo_conf_files }}"
      tags: [ shared, dotfiles, links ]

    - name: Scan for untracked but required configuration files/directories
      ansible.builtin.stat:
        path: "{{ item | expanduser }}"
      loop: "{{ untracked_conf_files }}"
      register: untracked_conf_files_stats

    - name: Warn that untracked but required configuration files/directories do not exist.
      ansible.builtin.debug:
        msg: |
          WARNING: '{{ item.item }}' could not be found.
          Create it or copy it from your old machine if you are migrating.
      loop: "{{ untracked_conf_files_stats.results }}"
      when: not item.stat.exists
      loop_control:
        label: "{{ item.item }}"
